name: Ares
version: '${project.version}'
main: me.vzhelev.ares.Ares
authors: [ ValentinZhelev ]
description: This plugin disables commands specified in the configuration and prevents granting the OP authority to people not authorized in the plugin configuration.
commands:
  ares:
    usage: /<command>
    description: reload config
