name: Ares
version: '${project.version}'
main: me.codedcrown.ares.Ares
api-version: 1.18
authors: [ ValentinZhelev ]
description: This plugin removes players with OP rights not added to the configuration.
commands:
  ares:
    usage: /<command>
    description: reload config